version: "3"
services:
  backend:
    image: lordrahl/coop-backend
    container_name: "coop-backend"
    build:
      context: ../
      dockerfile: ./.docker/app.dockerfile
    volumes:
      - ../:/app
    env_file:
      - ../.envs/app.env
    ports:
      - 8000:80
    networks:
      - coop-network
    depends_on:
      - database
      - redis

  database:
    image: mysql:5.7
    container_name: "coop-db"
    ports:
      - "3308:3306"
    env_file:
      - ../.envs/mysql.env
    volumes:
      - coop-db-volume:/var/lib/mysql
    networks:
      - coop-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "coop_phpma"
    depends_on:
      - database
    ports:
      - 8080:80
    links:
      - database
      - redis
    environment:
      PMA_HOST: database
    env_file:
      - ../.envs/mysql.env

    networks:
      - coop-network
  redis:
    image: redis
    container_name: "coop-redis"
    ports:
      - 6379:6379
    volumes:
      - "./redis-data:/data"

    networks:
      - coop-network

networks:
  coop-network:
    driver: bridge

volumes:
  coop-db-volume:
