---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: quest
  name: quest-logs-pv
  labels:
    tier: storage
    app: quest-logs
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  storageClassName: quest-logs-pv
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: "/srv/nfs/questdata/logs"
    server: nfs-server.example.com


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quest-logs-pvc
  namespace: quest
  labels:
    tier: storage
    app: quest-logs
spec:
  storageClassName: quest-logs-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
