apiVersion: v1
kind: ConfigMap
metadata:
  name: quest-config
  namespace: quest
  labels:
    tier: backend
    name: quest-config
data:
  APP_NAME: "laravel"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_LOG_LEVEL: "info"

  LOG_FILE: "/var/www/html/storage/logs"
  DB_HOST: "quest-db"
  DB_DATABASE: "quest"
  DB_USERNAME: "quest_user"
  REDIS_HOST: "quest-redis"

  MAIL_DRIVER: "log"
  MAIL_HOST: ""
  MAIL_PORT: "587"
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  MAIL_ENCRYPTION: "tls"

  CACHE_DRIVER: redis
  QUEUE_DRIVER: redis
  SESSION_DRIVER: redis
