on: [push]
name: Build coopify Backend
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout The code'
        uses: actions/checkout@master

      - name: 'Build and push The Image'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile:  ./.docker/app.dockerfile
          repository: lordrahl/quest-backend
          tags: latest
          push: true

